/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.103
 * Generated at: 2020-07-16 09:11:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.player.iframe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.lang.reflect.Array;
import de.uhh.l2g.plugins.service.VideoLocalServiceUtil;
import de.uhh.l2g.plugins.model.Video;
import de.uhh.l2g.plugins.model.impl.VideoImpl;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org   /TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<script type=\"text/javascript\" src=\"/lecture2go-portlet/js/jquery-2.1.4.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/lecture2go-portlet/player/jwplayer-7.12.13/jwplayer.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">jwplayer.key=\"201IIc3/RasApk0L1+d1fv9pi5UCUsF6VvHj1C+EfkI=\";</script>\n");
      out.write("\n");
      out.write("\t<title>Lecture2o-Embed</title>\n");
      out.write("\t<style type=\"text/css\">\n");
      out.write("\n");
      out.write("\t\t.jw-controlbar-center-group {\n");
      out.write("\t\t    width: 100% !important;\n");
      out.write("\t\t    padding: 0 .5em;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t.jw-controlbar {\n");
      out.write("\t\t    width: calc(100% - 100px) !important;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.jw-text-track-cue.jw-reset {\n");
      out.write("\t\t    line-height: 1.4em;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t.jw-background-color {\n");
      out.write("   \t\tbackground-color: rgba(33, 33, 33, 0.8);\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.jw-skin-seven .jw-dock-button {\n");
      out.write("\t\t    border-radius: 0em !important;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.jw-dock-button.jw-background-color.jw-reset {\n");
      out.write("\t\t    bottom: -40px;\n");
      out.write("\t\t    margin: 0 0 0 -11px;\n");
      out.write("\t\t    position: absolute;\n");
      out.write("\t\t    width: 100%;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.jw-icon.jw-dock-image.jw-reset::before {\n");
      out.write("\t\t    color: #fff;\n");
      out.write("\t\t    content: \"Lecture2Go\";\n");
      out.write("\t\t    float: right;\n");
      out.write("\t\t    font-family: arial;\n");
      out.write("\t\t    font-size: 15px;\n");
      out.write("\t\t    font-weight: bold;\n");
      out.write("\t\t    margin-right: 8px;\n");
      out.write("\t\t    margin-top: 11px;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.jw-overlay::before {\n");
      out.write("\t\t    background-color: rgba(0, 0, 0, 0);\n");
      out.write("\t\t    bottom: 0;\n");
      out.write("\t\t    content: \" \";\n");
      out.write("\t\t    left: -50%;\n");
      out.write("\t\t    position: absolute;\n");
      out.write("\t\t    top: 100px;\n");
      out.write("\t\t    width: 100%;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.jw-dock-button .jw-overlay {\n");
      out.write("\t\t    display: none;\n");
      out.write("\t\t    margin-top: -63px !important;\n");
      out.write("\t\t    margin-right: 5px !important;\n");
      out.write("\t\t    font-size: 14px !important;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.jw-skin-seven .jw-dock .jw-overlay, .jw-skin-seven .jw-skip {\n");
      out.write("\t\t    border-radius: 0em !important;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t.jw-dock-image:hover {\n");
      out.write("   \t\topacity: 1;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t</style>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tfunction getOpenAccess(){\n");
      out.write("\t\t\tconsole.log(\"open access\");\n");
      out.write("\t\t\tvar oa = $(\"#openaccess\").attr('value');\n");
      out.write("\t\t\treturn oa;\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction getParentUrl() {\n");
      out.write("\t\t    var isInIframe = (parent !== window),\n");
      out.write("\t\t        parentUrl = \"null\";\n");
      out.write("\t\t    if (isInIframe) {\n");
      out.write("\t\t        parentUrl = document.referrer;\n");
      out.write("\t\t    }\n");
      out.write("\t\t    return parentUrl;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t</script>\n");
      out.write("\t<!-- Piwik -->\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t var _paq = _paq || [];\n");
      out.write("\t\t // tracker methods like \"setCustomDimension\" should be called before \"trackPageView\"\n");
      out.write("\t\t _paq.push(['trackPageView']);\n");
      out.write("\t\t _paq.push(['enableLinkTracking']);\n");
      out.write("\t\t (function() {\n");
      out.write("\t\t   var u=\"//www.piwik.uni-hamburg.de/\";\n");
      out.write("\t\t   _paq.push(['setTrackerUrl', u+'piwik.php']);\n");
      out.write("\t\t   _paq.push(['setSiteId', '137']);\n");
      out.write("\t\t   var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];\n");
      out.write("\t\t   g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);\n");
      out.write("\t\t })();\n");
      out.write("\t\t</script>\n");
      out.write("\t<!-- End Piwik Code -->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	Video video = new VideoImpl();
	Long videoId = new Long(0);
	String start = null;
	String end = null;
	String[] al = new String[3];
	String[] s = new String[3];
	
	if (request.getParameterMap().containsKey("v")) {
			
		try{//parameter is long
			videoId = new Long(request.getParameter("v"));
			//not allowed for requested long id and closed access
			//becouse cloased access id should be ecoded string
			video = VideoLocalServiceUtil.getVideo(videoId);
			if (video.getOpenAccess()==0)video.setVideoId(0);
		}catch(NumberFormatException e){//parameter is path
			al = request.getParameter("v").split("/");
			// it can be on open access or closed access video !!!
	
			//for a closesed access video, check this
			//don't forget cases in commsy like this -> 37l2gbar8265/00.000_video-22005_2017-10-06_13-00.mp4
			if(al.length==1){
				int t =  al[0].split("_").length;
				if(t==4)videoId = VideoLocalServiceUtil.getByFilename(al[0]).iterator().next().getVideoId();
				else videoId = VideoLocalServiceUtil.getBySecureUrl(al[0]).getVideoId();
			}
			if(al.length==2){
				int t =  al[1].split("_").length;
				if(t==4)videoId = VideoLocalServiceUtil.getByFilename(al[1]).iterator().next().getVideoId();
				else videoId = VideoLocalServiceUtil.getBySecureUrl(al[1]).getVideoId();
			}
	
			//has time parameters
			if(al.length==3){
				try{
					s = request.getQueryString().split("/");
					videoId = new Long(s[0].split("=")[1]);
					start = s[1];
					end = s[2];
				}catch(Exception a){}
			}
			//
			try {
				video = VideoLocalServiceUtil.getVideo(videoId);
			} catch (Exception e2) {
				//
			}		
		}
	}


      out.write("\n");
      out.write("<body>\n");
      out.write("<input type=\"hidden\" id=\"openaccess\" name=\"openaccess\" value=\"");
      out.print(video.getOpenAccess());
      out.write("\">\n");
      out.write("\n");
      out.write("\t");
if(video.getVideoId()>0){ 
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div id=\"player1\"></div>\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\t\t\tvar isCitation=false;\n");
      out.write("\t\t\t\t\t// herausfinden ob es ein tablet/smartphone ist\n");
      out.write("\t\t\t        var isTouchDevice = 'ontouchstart' in document.documentElement;\n");
      out.write("\n");
      out.write("\t\t\t        // Start- und Endzeit der Zitatfunktion ermitteln (Durch die URL Parameter)\n");
      out.write("\t\t\t        var fs=");
      out.print(start);
      out.write(";\n");
      out.write("\t\t\t        var fe= ");
      out.print(end);
      out.write(";\n");
      out.write("\n");
      out.write("\t\t\t        if(fs>0 && fe>0 && fe>fs){\n");
      out.write("\t\t\t\t        var frameStart = ");
      out.print(start);
      out.write(";\n");
      out.write("\t\t\t\t        var frameEnd = ");
      out.print(end);
      out.write(";\n");
      out.write("\t\t\t\t        isCitation = true;\n");
      out.write("\t\t\t        }\n");
      out.write("\n");
      out.write("\t\t\t\t\tvar vttTracks =");
      out.print(video.getJsonPlayerTracks());
      out.write(";\n");
      out.write("\t\t\t        //\n");
      out.write("\n");
      out.write("\t\t\t\t\tvar img = \"");
      out.print(video.getImage());
      out.write("\";\n");
      out.write("\t\t\t        jwplayer('player1').setup({\n");
      out.write("\t\t\t            width: \"100%\",\n");
      out.write("       \t\t\t    \theight: \"100%\",\n");
      out.write("\t\t\t            aspectratio: \"16:9\",\n");
      out.write("\t\t\t            image: img,\n");
      out.write("\t\t\t            sources: ");
      out.print(video.getJsonPlayerUris());
      out.write(",\t\t            \n");
      out.write("\t\t\t            tracks: vttTracks,\t\t\t\t        \n");
      out.write("\t\t\t            hlshtml: true,\n");
      out.write("\t\t\t            androidhls: true\n");
      out.write("\t\t\t        }).onReady(function() {\n");
      out.write("\n");
      out.write("\t\t\t            if (frameStart && frameEnd) {\n");
      out.write("\t\t\t                // Sollten sich die Start- und Endzeit in den URL Parametern befinden\n");
      out.write("\t\t\t                // wird in diesen Abschnitt dafür gesorgt das man auch nur das Entsprechende\n");
      out.write("\t\t\t                // Videomaterial zu sehen bekommt\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t                // iOS und Android unterstützen seek nur wenn der Nutzer\n");
      out.write("\t\t\t                // selbst manuell das vide gestartet hat. Wir werden den start des Zitates\n");
      out.write("\t\t\t                // später anders lösen\n");
      out.write("\t\t\t                if (!isTouchDevice) {\n");
      out.write("\t\t\t                \tjwplayer().on('firstFrame', function() {\n");
      out.write("\t\t\t                \t\tjwplayer().play();\n");
      out.write("\t\t\t                \t\tjwplayer().seek(frameStart);\n");
      out.write("\t\t\t                \t});\n");
      out.write("\t\t\t                }\n");
      out.write("\t\t\t            }\n");
      out.write("\n");
      out.write("\t\t\t            // Event listener alle 100 ms während playback\n");
      out.write("\t\t\t            jwplayer().onTime( function(event){\n");
      out.write("\n");
      out.write("\t\t\t                // Sicher stellen, dass der gewählte Zeitraum eingehalten wird\n");
      out.write("\n");
      out.write("\t\t\t                var pos =  Math.floor(event.position);\n");
      out.write("\n");
      out.write("\t\t\t                if (pos < frameStart && isTouchDevice) {\n");
      out.write("\t\t\t                    // Nur unter iOS und Android nötig,\n");
      out.write("\t\t\t                    jwplayer().seek(frameStart);\n");
      out.write("\t\t\t                } else if (pos > frameEnd) {\n");
      out.write("\t\t\t                    jwplayer().seek(frameStart);\n");
      out.write("\t\t\t                    jwplayer().pause();\n");
      out.write("\t\t\t                }\n");
      out.write("\t\t\t            });\n");
      out.write("\n");
      out.write("\t\t\t            // Diese Stelle ist wiederum nur auf PC nötig.\n");
      out.write("\t\t\t            // Hiermit wird verhindert, dass der Nutzer per Tastatur\n");
      out.write("\t\t\t            // aus den Zitatsbereich herausspult\n");
      out.write("\t\t\t            if (!isTouchDevice) {\n");
      out.write("\t\t\t                jwplayer().onSeek( function(event){\n");
      out.write("\t\t\t                    var pos =  event.position;\n");
      out.write("\n");
      out.write("\t\t\t                    if (Math.ceil(pos) < Math.ceil(frameStart) || Math.ceil(pos) > Math.ceil(frameEnd)) {\n");
      out.write("\t\t\t                        jwplayer().seek(frameStart);\n");
      out.write("\t\t\t                        jwplayer().pause();\n");
      out.write("\t\t\t                    }\n");
      out.write("\t\t\t                });\n");
      out.write("\t\t\t            }\n");
      out.write("\n");
      out.write("\t\t\t            $('#fullVideo').show();\n");
      out.write("\n");
      out.write("\t\t\t        });\n");
      out.write("\t\t\t        //\n");
      out.write("\t\t\t        var tit=\"Lecture2Go\";\n");
      out.write("\t\t\t        if(isCitation){\n");
      out.write("\t\t\t        \ttit=\"Zitat2Go\";\n");
      out.write("\t\t\t        }\n");
      out.write("\t\t\t        jwplayer().addButton(\n");
      out.write("\t\t\t        \t\"\",\n");
      out.write("\t\t\t        \t\"Dieses Video auf Lecture2Go ansehen\",\n");
      out.write("\t\t\t        \tfunction() {\n");
      out.write("\t\t\t        \t\t//stop player\n");
      out.write("\t\t\t        \t\tjwplayer().stop();\n");
      out.write("\t\t\t        \t\t//open web site\n");
      out.write("\t\t\t        \t\t");

			        			String url = "";
			        			if(video.getOpenAccess()==1)url=video.getUrl();
			        			else url="";
			        		
			        		if(!url.isEmpty()){
			        		
      out.write("\n");
      out.write("\t\t\t                window.open('");
      out.print(url);
      out.write("');\n");
      out.write("\t\t\t                ");
}
      out.write("\n");
      out.write("\t\t\t            },\n");
      out.write("\t\t\t            tit\n");
      out.write("\t\t\t        );\n");
      out.write("\t\t</script>\n");
      out.write("\t");
}
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
